# src/compliance.py

class RegulatoryCompliance:
    def __init__(self, alerts):
        """
        Initialize the compliance module with the detected alerts.

        :param alerts: List of alert dictionaries generated by MoneyLaunderingDetector
        """
        self.alerts = alerts

    def generate_report(self):
        """
        Generate a compliance report based on detected alerts.
        """
        print("\n📝 Compliance Report")
        if self.alerts:
            for alert in self.alerts:
                print(f" - Account {alert['account_id']} | {alert['alert_id']} | {alert['reason']}")
        else:
            print("✅ No compliance issues found.")
